/**
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.ui.contentassist;

import co.classlayout2frontend.c2fdsl.ui.contentassist.AbstractC2fDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class C2fDSLProposalProvider extends AbstractC2fDSLProposalProvider {
}
