/**
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl;

import co.classlayout2frontend.c2fdsl.C2fDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class C2fDSLStandaloneSetup extends C2fDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new C2fDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
