/**
 *
 * $Id$
 */
package angularIonic.validation;

import angularIonic.Input;
import angularIonic.Output;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link angularIonic.Component}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateInputs(EList<Input> value);
	boolean validateOutputs(EList<Output> value);
	boolean validateClass(angularIonic.Class value);
}
