/*
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.ui;

import co.classlayout2frontend.c2fdsl.ui.internal.C2fdslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class C2fDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return C2fdslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return C2fdslActivator.getInstance().getInjector(C2fdslActivator.CO_CLASSLAYOUT2FRONTEND_C2FDSL_C2FDSL);
	}
	
}
