/*
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.parser.antlr;

import co.classlayout2frontend.c2fdsl.parser.antlr.internal.InternalC2fDSLParser;
import co.classlayout2frontend.c2fdsl.services.C2fDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class C2fDSLParser extends AbstractAntlrParser {

	@Inject
	private C2fDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalC2fDSLParser createParser(XtextTokenStream stream) {
		return new InternalC2fDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Project";
	}

	public C2fDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(C2fDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
