/**
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class C2fDSLQuickfixProvider extends DefaultQuickfixProvider {
}
