/*
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class C2fDSLProposalProvider extends AbstractC2fDSLProposalProvider {
}
