/*
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.ui.tests;

import co.classlayout2frontend.c2fdsl.ui.internal.C2fdslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class C2fDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return C2fdslActivator.getInstance().getInjector("co.classlayout2frontend.c2fdsl.C2fDSL");
	}

}
