/**
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.ide;

import co.classlayout2frontend.c2fdsl.ide.AbstractC2fDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class C2fDSLIdeModule extends AbstractC2fDSLIdeModule {
}
