/**
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.ide;

import co.classlayout2frontend.c2fdsl.C2fDSLRuntimeModule;
import co.classlayout2frontend.c2fdsl.C2fDSLStandaloneSetup;
import co.classlayout2frontend.c2fdsl.ide.C2fDSLIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class C2fDSLIdeSetup extends C2fDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    C2fDSLRuntimeModule _c2fDSLRuntimeModule = new C2fDSLRuntimeModule();
    C2fDSLIdeModule _c2fDSLIdeModule = new C2fDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_c2fDSLRuntimeModule, _c2fDSLIdeModule));
  }
}
