/**
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.validation;

import co.classlayout2frontend.c2fdsl.validation.AbstractC2fDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class C2fDSLValidator extends AbstractC2fDSLValidator {
}
