/*
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class C2fDSLUiModule extends AbstractC2fDSLUiModule {
}
