/*
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractC2fDSLScopeProvider extends DelegatingScopeProvider {
}
