/**
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl.scoping;

import co.classlayout2frontend.c2fdsl.scoping.AbstractC2fDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class C2fDSLScopeProvider extends AbstractC2fDSLScopeProvider {
}
