/*
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class C2fDSLRuntimeModule extends AbstractC2fDSLRuntimeModule {
}
