/*
 * generated by Xtext 2.12.0
 */
package co.classlayout2frontend.c2fdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class C2fDSLStandaloneSetup extends C2fDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new C2fDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
